// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADPILDgSKT0NzN4zNjYgmoIt8z-_MgbQY',
    appId: '1:1057759872334:android:ebb2c549a09213fd380a1f',
    messagingSenderId: '1057759872334',
    projectId: 'd-whales',
    storageBucket: 'd-whales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaqcKNWNK2Fna1tbIt1SQmjSUmP_dy_0g',
    appId: '1:1057759872334:ios:80fa396b7855eeb6380a1f',
    messagingSenderId: '1057759872334',
    projectId: 'd-whales',
    storageBucket: 'd-whales.firebasestorage.app',
    iosBundleId: 'com.example.myHeadspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaqcKNWNK2Fna1tbIt1SQmjSUmP_dy_0g',
    appId: '1:1057759872334:ios:80fa396b7855eeb6380a1f',
    messagingSenderId: '1057759872334',
    projectId: 'd-whales',
    storageBucket: 'd-whales.firebasestorage.app',
    iosBundleId: 'com.example.myHeadspace',
  );
}
